### ISSUE TITLE
怎样找到完整的数据集

### ISSUE THREAD

**Issue by Longmeix** [zjukg/MuDoK#1]
作者您好，感谢您的工作，对我非常有启发！

为获得初始token text embedding，我尝试运行文件`
/extract_amazon_emb.py`，代码中需要`metadata.json`和`item2text.json`文件，但我未在项目中找到，请问您可以上传它们吗？
``` python
# in ./extract_amazon_emb.py
kg = json.load(open("datasets/{}/metadata.json".format(dataset), "r")) 
text_map = json.load(open("data_utils/item2text.json", "r"))
```

**Comment by Zhang-Each** [comment]
您好，这部分数据规模较大，需要一些额外的时间整理和上传，可能还需要一段时间才能完整开源，请您谅解。

**Comment by Longmeix** [comment]
感谢回复，期待你们的更新~
